### ISSUE TITLE
Hiding unique keys and moving the flask config to another file.

### ISSUE THREAD

**Issue by JM1F** [BUAdvDev2023/Product-API#11]
Hi,

The repository is currently public and everyone outside BUAdvDev can see the flask configuration, including the secret key.

![image](https://github.com/BUAdvDev2023/Product-API/assets/71614127/cf1a486a-75e3-4da5-8f4c-6fe06f2bb050)

It is generally good practice to move the config settings to a separate file (config.py) and include it in your .gitignore so it does not get committed.

This is a ditto of: https://github.com/BUAdvDev2023/Rest-Auth-API/issues/19, but should still apply to the product API also.

**Comment by Jesus-15** [comment]
Same answer as https://github.com/BUAdvDev2023/Rest-Auth-API/issues/19. Thanks
